version: "3.8"
services:
  mysqlserver:
    build: ./wildforge-api/mysql
    image: mysql
    container_name: wildforge-db
    ports:
      - 3306:3306
    env_file:
      - ./env/mysql.env
    networks:
      - wildforge-network

  backend:
    build: ./wildforge-api
    image: wildforge-api
    container_name: wildforge-api
    ports:
      - 8000:8000
    env_file:
      - ./env/backend.env
    networks:
      - wildforge-network
    depends_on:
      - mysqlserver
    
  
  # frontend:
  #   build: ./wildforge-app
  #   image: wildforge-app
  #   container_name: wildforge-app
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - ./env/frontend.env
  #   volumes:
  #     - ./wildforge-app/src:/app/src
  #   depends_on:
  #     - backend


networks:
  wildforge-network:
    driver: bridge
